global:
  newer_than: "2d" #ensure string

newsletters:
  - name: "TLDR AI"
    email: "dan@tldrnewsletter.com"

  - name: "TLDR Founders"
    email: "dan@tldrnewsletter.com"

preferences:
  interests: # show items that match *any* of these
    - "agents"
    - "vector search"
    - "RAG"
    - "OpenSearch"
    - "LangGraph"
    - "NotebookLM"
  disinterests: # hide items that mention any of these
    - "crypto"
    - "NFT"
    - "jobs"
    - "sponsor"
    - "web3"
